modLoader="javafml"
loaderVersion="[4,)"
license="Custom Licence"

[[mods]]
modId="alcohol_industry"
version="1.0"
displayName="Create: Alcohol Industry"
authors="MrPotato"
description=""
logoFile="logo.png"

[[dependencies."alcohol_industry"]]
    modId="neoforge"
    type="required"
    versionRange="(21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies."alcohol_industry"]]
    modId="minecraft"
    type="required"
    versionRange="1.21.1"
    ordering="NONE"
    side="BOTH"

[[dependencies."alcohol_industry"]]
    modId="create"
    type="required"
    versionRange="[6.0.9,6.1.0)"
    ordering="NONE"
    side="BOTH"